name: Contrib
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Script
      run: |
        echo Downloading Script...
        wget https://raw.githubusercontent.com/MattTheTekie/MattTheTekie/master/Personal-Scripts/org_contributors.sh
        wget https://raw.githubusercontent.com/MattTheTekie/MattTheTekie/master/Personal-Scripts/org.sh 
        wget https://github.com/sterlp/svg2png/releases/download/v1.2.1/svg2png
        chmod +x org_contributors.sh
        chmod +x org.sh
        chmod +x svg2png

    - name: Run Script
      run: |
           ./org_contributors.sh
           ./svg2png contributors.svg
           cd profile
           ../org.sh
           cd ..
           rm contributors.svg
           rm svg2png
           rm org.sh
           rm org_contributors.sh
        
    - name: Push Contributors
      run: |
        rm -rf .git/
        git init
        git remote add origin https://github.com/VenithNET/.github/
        git add .
        git commit -m "contib"
        git push -f origin main
        git config --global user.email "you@example.com"
        git config --global user.name "MattTheTekie"
