name: Contrib
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Script
      run: |
        echo Downloading Script...
        wget https://raw.githubusercontent.com/MattTheTekie/MattTheTekie/master/Personal-Scripts/org_contributors.sh
        chmod +x org_contributors.sh

    - name: Run Script
      run: ./org_contributors.sh
           convert contributors.svg contributors.png
           rm contributors.svg
        
    - name: Push Contributors PNG
      run: |
        git config --global user.name "MattTheTekie"
        git add contributors.png
        git commit -m "Add contributors.png"
        git push origin HEAD:main
